# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'books.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\"\x07\n\x05\x45mpty\"1\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"\x19\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x08\x42ookList\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Book2i\n\x0b\x42ookService\x12\x1d\n\x08GetBooks\x12\x06.Empty\x1a\t.BookList\x12\"\n\x0bGetBookById\x12\x0c.BookRequest\x1a\x05.Book\x12\x17\n\x07\x41\x64\x64\x42ook\x12\x05.Book\x1a\x05.Bookb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=15
  _globals['_EMPTY']._serialized_end=22
  _globals['_BOOK']._serialized_start=24
  _globals['_BOOK']._serialized_end=73
  _globals['_BOOKREQUEST']._serialized_start=75
  _globals['_BOOKREQUEST']._serialized_end=100
  _globals['_BOOKLIST']._serialized_start=102
  _globals['_BOOKLIST']._serialized_end=134
  _globals['_BOOKSERVICE']._serialized_start=136
  _globals['_BOOKSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
