# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: question_answer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'question_answer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15question_answer.proto\x12\x0equestionanswer\".\n\tQARequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"G\n\nQAResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\x32Y\n\x15QuestionAnswerService\x12@\n\x07Predict\x12\x19.questionanswer.QARequest\x1a\x1a.questionanswer.QAResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'question_answer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QAREQUEST']._serialized_start=41
  _globals['_QAREQUEST']._serialized_end=87
  _globals['_QARESPONSE']._serialized_start=89
  _globals['_QARESPONSE']._serialized_end=160
  _globals['_QUESTIONANSWERSERVICE']._serialized_start=162
  _globals['_QUESTIONANSWERSERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
