# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classification.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'classification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63lassification.proto\x12\x0e\x63lassification\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"4\n\nPrediction\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"@\n\rImageResponse\x12/\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x1a.classification.Prediction2d\n\x1aImageClassificationService\x12\x46\n\x07Predict\x12\x1c.classification.ImageRequest\x1a\x1d.classification.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=40
  _globals['_IMAGEREQUEST']._serialized_end=74
  _globals['_PREDICTION']._serialized_start=76
  _globals['_PREDICTION']._serialized_end=128
  _globals['_IMAGERESPONSE']._serialized_start=130
  _globals['_IMAGERESPONSE']._serialized_end=194
  _globals['_IMAGECLASSIFICATIONSERVICE']._serialized_start=196
  _globals['_IMAGECLASSIFICATIONSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
